2023-07-11 13:37:17,911 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Configure stats pid to 1634
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Loading settings from /Users/sohrabnamazinia/.config/wandb/settings
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Loading settings from /Users/sohrabnamazinia/Desktop/Summer 23/RA/RL/RL_Modular/wandb/settings
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_deep_policy.py', 'program': '/Users/sohrabnamazinia/Desktop/Summer 23/RA/RL/RL_Modular/train_deep_policy.py'}
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_init.py:_log_setup():507] Logging user logs to /Users/sohrabnamazinia/Desktop/Summer 23/RA/RL/RL_Modular/wandb/run-20230711_133717-c16308ow/logs/debug.log
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/sohrabnamazinia/Desktop/Summer 23/RA/RL/RL_Modular/wandb/run-20230711_133717-c16308ow/logs/debug-internal.log
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_init.py:init():547] calling init triggers
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_init.py:init():596] starting backend
2023-07-11 13:37:17,912 INFO    MainThread:1634 [wandb_init.py:init():600] setting up manager
2023-07-11 13:37:17,928 INFO    MainThread:1634 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-11 13:37:17,951 INFO    MainThread:1634 [wandb_init.py:init():606] backend started and connected
2023-07-11 13:37:18,024 INFO    MainThread:1634 [wandb_init.py:init():705] updated telemetry
2023-07-11 13:37:18,083 INFO    MainThread:1634 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-11 13:37:18,359 ERROR   MainThread:1634 [wandb_init.py:init():764] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-11 13:37:18,510 ERROR   MainThread:1634 [wandb_init.py:init():1172] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-07-11 13:37:19,520 WARNING MsgRouterThr:1634 [router.py:message_loop():77] message_loop has been closed
