
Using cpu device
Traceback (most recent call last):
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py", line 40, in _patch_env
    import shimmy  # pytype: disable=import-error
ModuleNotFoundError: No module named 'shimmy'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "c:\Users\ferti\Documents\RL_Modular\train_deep_policy.py", line 33, in <module>
    deep_agent = Agent(grid_world, deep_algorithm)
  File "c:\Users\ferti\Documents\RL_Modular\agents\deep_agent.py", line 25, in __init__
    self.model = DQN("MlpPolicy", env, verbose=1)
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\dqn\dqn.py", line 104, in __init__
    super().__init__(
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 110, in __init__
    super().__init__(
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\base_class.py", line 169, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\base_class.py", line 216, in _wrap_env
    env = _patch_env(env)
  File "C:\Users\ferti\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\patch_gym.py", line 42, in _patch_env
    raise ImportError(
ImportError: Missing shimmy installation. You an OpenAI Gym environment. Stable-Baselines3 (SB3) has transitioned to using Gymnasium internally. In order to use OpenAI Gym environments with SB3, you need to install shimmy (`pip install 'shimmy>=0.2.1'`).